spring:
  h2:
    console:
      enabled: true
      path: /h2-console
    autoconfigure:
      exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    url: jdbc:h2:tcp://localhost/~/TeamProj
    username: sa
    password:
    driver-class-name: org.h2.Driver

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace